version: "2"
# see https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - maintidx
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
linters.settings:
  maintidx:
    # Show functions with maintainability index lower than N.
    # A high index indicates better maintainability (it's kind of the opposite of complexity).
    # Default: 20
    under: 30
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
formatters:
  enable:
    - gci
    - gofumpt
formatters.settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kwo/crystal)
